import tkinter as tk
window=tk.Tk()
window.geometry("800x800")
def onclick():
    print(1)

chkvar1=tk.IntVar()
chkbtn1=tk.Checkbutton(text="Кухня",variable=chkvar1,onvalue=1,offvalue=0)
chkbtn1.grid(row=0,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=2,column=0)

chkvar2=tk.IntVar()
chkbtn2=tk.Checkbutton(text="Зал",variable=chkvar2,onvalue=1,offvalue=0)
chkbtn2.grid(row=4,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=5,column=0)

chkvar3=tk.IntVar()
chkbtn3=tk.Checkbutton(text="Прихожая",variable=chkvar3,onvalue=1,offvalue=0)
chkbtn3.grid(row=7,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=8,column=0)

chkvar4=tk.IntVar()
chkbtn4=tk.Checkbutton(text="Кладовка",variable=chkvar4,onvalue=1,offvalue=0)
chkbtn4.grid(row=10,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=11,column=0)
chkvar5=tk.IntVar()
chkbtn5=tk.Checkbutton(text="Комната 1",variable=chkvar5,onvalue=1,offvalue=0)
chkbtn5.grid(row=12,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=13,column=0)
chkvar6=tk.IntVar()
chkbtn6=tk.Checkbutton(text="Моя комната",variable=chkvar6,onvalue=1,offvalue=0)
chkbtn6.grid(row=14,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=15,column=0)

chkvar7=tk.IntVar()
chkbtn7=tk.Checkbutton(text="Туалет",variable=chkvar7,onvalue=1,offvalue=0)
chkbtn7.grid(row=16,column=0)
scl=tk.Scale(label="Яркость",from_=1,to=100,orient=tk.HORIZONTAL,length=200,width=10)
scl.grid(row=17,column=0)
window.mainloop()